name: okdock

services:
  okdock:
    build: .
    image: ghcr.io/vitorcdsouza/okdock:latest
    pull_policy: always
    container_name: okdock
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/games:/srv/games
    environment:
      OKDOCK_ROOT: /srv/games
      OKDOCK_MEMORY_RESERVE: 2g
      OKDOCK_LOG_LEVEL: info
